name: topictick
publish_to: "none"
description: A simple macOS app to remind topic revisions on a fixed spaced repetition schedule.

# Prevent accidental publishing to pub.dev.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.1.2
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  # Local notifications with macOS support
  flutter_local_notifications: ^19.4.0
  # Timezone support for accurate scheduling
  timezone: ^0.10.1

  # Cupertino icons for iOS/macOS style if needed
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
